# Generated by Django 2.2.6 on 2021-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('year_of_production', models.IntegerField(null=True)),
                ('rating', models.IntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
                ('genre', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('year_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(-1, 'I DONT KNOW'), (0, 'MAN'), (1, 'WOMAN')])),
                ('movies', models.ManyToManyField(to='filmweb_app.Movies')),
            ],
        ),
    ]
