# Generated by Django 2.2.6 on 2021-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('year_of_production', models.IntegerField(null=True)),
                ('rating', models.IntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
                ('genre', models.IntegerField(choices=[(0, 'Nie wiem'), (1, 'Komedia'), (2, 'Musical'), (3, 'Familijny'), (4, 'Film akcji'), (5, 'Przygodowy'), (6, 'Horror')])),
            ],
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('year_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(-1, 'Nie chcę podawać'), (0, 'Mężczyzna'), (1, 'Kobieta')])),
                ('movies', models.ManyToManyField(to='filmweb_app.Movies')),
            ],
        ),
    ]
